### ISSUE TITLE
LibUV should use win8-arm as the RID

### ISSUE THREAD

**Issue by davidfowl** [aspnet/libuv-build#15]
It currently places WinArm32 assets under win7-arm that is not a valid RID/platform configuration.

/cc @gkhanna79 

Moved from https://github.com/dotnet/corefx/issues/13311

**Comment by muratg** [comment]
I thought there were other problems with running kestrel on arm, but perhaps I'm wrong.  cc @moozzyk

**Comment by moozzyk** [comment]
libuv works fine on windows arm. It originally used win10-arm but I had to move it to win7-arm or to avoid issues during publish (https://github.com/aspnet/KestrelHttpServer/issues/340 + linked bugs). Note that the publish there was the dnu publish so things might work now. Hard to verify since AFAIK there is no runtime for arm at the moment.

**Comment by Petermarcu** [comment]
When do we think we can get a fix for this? I'd love to be able to do some hacking on Win10 IoT :)

**Comment by Petermarcu** [comment]
Simple change I think. I don't really know how to build and validate. https://github.com/aspnet/libuv-build/pull/16

**Comment by Petermarcu** [comment]
I also wasn't sure what branch is the right one to go against for vNext.

**Comment by moozzyk** [comment]
This has been fixed in both repos now.

**Comment by Petermarcu** [comment]
Thanks!

**Comment by gkhanna79** [comment]
But #16 seems to be open. Which PRs fixed them and where?

**Comment by moozzyk** [comment]
@gkhanna79 - I rebased on changes I made to update libuv to 1.10.0. This PR was pushed as a16eed2e8016b2d9452f22a5ca3c9c0d5d6f8e2e
